name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary
        choco install googlechrome

    - name: Download and install ChromeDriver
      run: |
        # Download the specified ChromeDriver version
        wget -N https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/win64/chromedriver-win64.zip
        # Unzip the downloaded file
        tar -xf chromedriver-win64.zip
        # Move ChromeDriver to the PATH directory
        move chromedriver.exe /usr/local/bin/
        # Add ChromeDriver to PATH
        set PATH=%PATH%;/usr/local/bin/

    - name: Run Robot Framework tests
      run: |
        robot testsuites/

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: output/

    - name: Publish test results as a GitHub Pages site
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: ${{ github.repository }}
        publish_dir: ./output/
